title: Mohamed Albirair
# logo: /
description: Implementation researcher, devoted R programmer, mathematical modeler, and a recognized research methods teacher.
show_downloads: true
theme: jekyll-theme-minimal
